_name_or_path:
    value: ""
_wandb:
    value:
        cli_version: 0.23.0
        e:
            03fovzyqe7qn7vby4pcy2ts7ps32921g:
                args:
                    - data.train_path=example_data/tokens.jsonl
                    - data.val_path=example_data/tokens.jsonl
                    - tokeniser=unit_hubert_25
                    - training_args.num_train_epochs=1
                    - training_args.per_device_train_batch_size=16
                    - training_args.gradient_accumulation_steps=4
                    - data.num_proc=32
                    - logger=wandb
                    - logger.entity=bauyrjanesq
                    - logger.project=slamkit-baseline
                    - training_args.output_dir=../outputs/baseline
                codePath: cli/train.py
                codePathLocal: cli/train.py
                cpu_count: 7
                cpu_count_logical: 14
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "42928701440"
                        used: "28815736832"
                email: bauyrjanesq@gmail.com
                executable: /home/bkairatuly/myenv/bin/python
                git:
                    commit: 388b40222a1736930dad5e6b231754217c69629a
                    remote: https://github.com/slp-rl/slamkit.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-2429d2db-ca8e-6714-ce37-73882985f053
                host: g1n6.cluster.wmi.amu.edu.pl
                memory:
                    total: "55799091200"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/bkairatuly/slamkit/cli/train.py
                python: CPython 3.10.12
                root: /home/bkairatuly/slamkit
                slurm:
                    job_id: "37781"
                startedAt: "2025-11-17T16:18:53.300697Z"
                writerId: 03fovzyqe7qn7vby4pcy2ts7ps32921g
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 84
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 84
            "3":
                - 3
                - 7
                - 13
                - 16
                - 19
                - 62
                - 66
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.44.2
            "9":
                "1": transformers_trainer
            "12": 0.23.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value: null
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
base_config:
    value:
        _name_or_path: facebook/opt-125m
        _remove_final_layer_norm: false
        activation_dropout: 0
        activation_function: relu
        add_cross_attention: false
        architectures:
            - OPTForCausalLM
        attention_dropout: 0
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: 1
        chunk_size_feed_forward: 0
        cross_attention_hidden_size: null
        decoder_start_token_id: null
        diversity_penalty: 0
        do_layer_norm_before: true
        do_sample: false
        dropout: 0
        early_stopping: false
        enable_bias: true
        encoder_no_repeat_ngram_size: 0
        eos_token_id: 1
        exponential_decay_length_penalty: null
        ffn_dim: 3072
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        hidden_size: 768
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        init_std: 0.02
        is_decoder: false
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        layer_norm_elementwise_affine: true
        layerdrop: 0
        length_penalty: 1
        max_length: 20
        max_position_embeddings: 2048
        min_length: 0
        model_type: opt
        no_repeat_ngram_size: 0
        num_attention_heads: 12
        num_beam_groups: 1
        num_beams: 1
        num_hidden_layers: 12
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        pad_token_id: 0
        prefix: </s>
        problem_type: null
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        sep_token_id: null
        suppress_tokens: null
        task_specific_params: null
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: null
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        use_cache: true
        vocab_size: 50272
        word_embed_proj_dim: 768
base_model_name:
    value: facebook/opt-125m
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
cont_training:
    value: false
cross_attention_hidden_size:
    value: null
data:
    value:
        chunk_units_min_length: null
        num_proc: 32
        packing: false
        sample_units_max_length: null
        saved_ds_path: null
        train_path: example_data/tokens.jsonl
        val_path: example_data/tokens.jsonl
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: false
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dropout:
    value: 0
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 1000
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: null
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layerdrop:
    value: 0
learning_rate:
    value: 0.001
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logger:
    value:
        entity: bauyrjanesq
        group: null
        project: slamkit-baseline
        report_to: wandb
        resume: null
        run_id: null
        save_code: false
logging_dir:
    value: ../outputs/baseline/runs/Nov17_17-18-52_g1n6.cluster.wmi.amu.edu.pl
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value:
        min_lr: 5e-05
lr_scheduler_type:
    value: cosine_with_min_lr
max_grad_norm:
    value: 0.5
max_length:
    value: 20
max_position_embeddings:
    value: 2048
max_steps:
    value: -1
max_token_id_count:
    value: null
metric_for_best_model:
    value: null
min_length:
    value: 0
min_token_id_count:
    value: null
model:
    value:
        config_args:
            attention_dropout: 0
            attn_implementation: null
            base_model_name: facebook/opt-125m
            bos_token_id: 1
            dropout: 0
            eos_token_id: 1
            layerdrop: 0
            pad_token_id: 0
            torch_dtype: null
            trust_remote_code: null
            twist_init: true
            use_cache: false
            use_safetensors: null
            vocab_size: 502
        context_len: 512
        pretrained_model: null
        tlm_type: twist
model/num_parameters:
    value: 87015936
model_type:
    value: speech_language_model
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ../outputs/baseline
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 16
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: baseline
run_time:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokeniser:
    value:
        feature_extractor:
            cache_path: null
            compile: false
            kmeans_path: https://dl.fbaipublicfiles.com/textless_nlp/twist/speech_tokenizer/mhubert_base_25hz_cp_mls_cv_sp_fisher_L11_km500.bin
            layer: 11
            load_config_only: false
            num_units: 500
            pretrained_model: slprl/mhubert-base-25hz
        feature_extractor_type: hubert
        params:
            bos_eos_token_id: 1
            dedup: true
            load_fe: false
            num_units: 500
            pad_token_id: 0
        requires_meta: false
        tokeniser_type: unit
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
train_max_tokens:
    value: null
training_args:
    value:
        bf16: true
        dataloader_num_workers: 4
        ddp_find_unused_parameters: false
        eval_accumulation_steps: null
        eval_steps: 1000
        eval_strategy: steps
        gradient_accumulation_steps: 4
        group_by_length: false
        learning_rate: 0.001
        lr_scheduler_kwargs:
            min_lr: 5e-05
        lr_scheduler_type: cosine_with_min_lr
        max_grad_norm: 0.5
        max_token_id_count: null
        min_token_id_count: null
        num_train_epochs: 1
        output_dir: ../outputs/baseline
        per_device_eval_batch_size: 8
        per_device_train_batch_size: 16
        save_total_limit: 2
        torch_compile: false
        use_cpu: false
        warmup_ratio: 0.01
        warmup_steps: 100
transformers_version:
    value: 4.44.2
trust_remote_code:
    value: null
twist_init:
    value: true
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
use_safetensors:
    value: null
vocab_size:
    value: 502
warmup_ratio:
    value: 0.01
warmup_steps:
    value: 100
weight_decay:
    value: 0
